sugarcube-2:
  macros:
    showcycle:
      name: showcycle
    showmeter:
      name: showmeter
    newcycle:
      name: newcycle
      container: true
    phase:
      name: phase
    newmeter:
      name: newmeter
      container: true
    animation:
      name: animation
    sizing:
      name: sizing
    colors:
      name: colors
    dialog:
      name: dialog
      container: true
    skillui:
      name: skillmenu
    modifystat:
      name: modifystat
    they:
      name: they
    them:
      name: them
    theirs:
      name: theirs
    their:
      name: their
    themself:
      name: themself
    person:
      name: person
    advancetime:
      name: advancetime
    fancy:
      name: fancy
      container: true
    newinv:
      name: newinv
    inv:
      name: inv
    item:
      name: item
      container: true
    consumable:
      name: item
      container: true
    description:
      name: description
    unique:
      name: unique
    permanent:
      name: permanent